### PR TITLE
Add group option to rlabel()

### PR DESCRIPTION
**Pull request by pavel-fibich**
Dear spatstat developers,

I am suggesting to add group option in rlabel(), to enable random labeling with groups (eg. relabel DBH within species).

_Motivation:_ image you have trees over the plot, marks are species identity and DBH. I would like to do random labeling that will leave species on the original/observed positions, but relabel only DBH marks within species. So I would like to have something like: rlabel(x, group="species"), where x is ppp with two marks, DBH and species. Actualy, rlabel() for data.frame marks changes positions of marks (it sample()s rows, so eg. for DBH and species marks does not break distributions of DBH over species, but it changes their positions ).

_Coding:_ I just add (after you calling replicate) check for group option (group will be the name of the column in data.frame, eg. "species"), if group is not specified nothing changes. Then I get order of original/observed group marks and on each of random/null community in Y, I changed order according group to be the same in the observed pattern. Your original replicate relabel individuals over the plot, my sorting just move species on the original positions, but now they can have different DBH marks, but species are on the original/observed positions. I made several tests and checks.

What do you thing?

Best regards and thank you for your great work, Pavel

### CODE REVIEW

**Comment by baddstats** [comment]
Thanks for your suggestion.

Your code would implement the default case `permute=TRUE` but not the case `permute=FALSE` (where presumably the marks should be resampled with replacement within each group). I will implement some suitable code.

**Comment by pavel-fibich** [comment]
Great, thank you for considering. You are right, the code will not work with permute=FALSE. Without using additional packages, following code can be used (for group and permute=FALSE, after that my ordering code must be called):
`      Y <- replicate(nsim, X %mark% do.call(rbind, lapply(split(labels, labels[,group]), function(x) x[sample(1:nrow(x), nrow(x),replace=TRUE), ])), simplify = FALSE)`
If you are interested, I can commit whole improved function.

**Comment by baddstats** [comment]
Implemented in a slightly different way.

**Comment by pavel-fibich** [comment]
Thank you for implementing group option.

**Pull request closed without merging**
