### PR TITLE
Added a few new ppx tools.

### PR DESCRIPTION
**Pull request by rubak**
I needed some tools in connection with a new ad hoc simulation procedure for DPPs which I will hopefully finish within too long. Not sure about the names of the functions etc. Didn't write the docs and full testing yet (the script tests/ppxextra.R also needs an `require(spatstat)` to actually work). I would like some feedback/ideas. Maybe `subsetclip` should not be a separate function, but just an extra argument `clip` in `[.ppx`? If `X` is the `ppx` and the clipped region is empty should we simply set `X$domain <- NULL`?

Please don't accept the pull request before we have finished discussing and I have a chance to add some commits to the pull request...

### CODE REVIEW

**Comment by baddstats** [comment]
That all looks OK to me, except to ask why you wanted to have methods for `base::scale` instead of  `spatstat::rescale`. (That could be confusing). 
Yes, I would favour making `subsetclip` a block of code inside `[.ppx`, if only so that it will be easier to associate with `ppx` objects.

**Comment by rubak** [comment]
I will put the clipping inside `[.ppx`. Do you think setting domain to `NULL` is the right solution for empty intersections?

I chose `base::scale` since I need to rescale each coordinate differently. Typically I need to rescale any general box to the unit box. I first thought it would be more in line with spatstat to do this with `affine`, but I wouldn't be able to handle a general affine transformation of the `boxx` domain. Should I move this to `affine.ppx` and just say that `mat` has to be a diagonal matrix (or a vector representing the diagonal) so I avoid any rotation/shear?

**Comment by baddstats** [comment]
Hm. The code is fine, I'm just not sure how to resolve the names of the functions..

I have to submit a new version of `spatstat` to CRAN this week, to fix a problem with the package checker, so I suggest we leave this branch hanging for the moment, i.e. not merge it, at least until after I submit to CRAN.

**Comment by rubak** [comment]
Sounds good. No rush from my side.

**Comment by rubak** [comment]
Yes, I will change to `affine`. As mentioned this was what I was most i doubt about.

**Comment by rubak** [comment]
Thanks @baddstats 
I forgot to change from `scale` to `affine`. Sorry about that. Should I do that now that you have merged?

**Pull request merged**
